theme: jekyll-theme-cayman
title: How to install Python on Windows with VS Code [Tutorial]
description: A newbie guide to start with Python on Windows, including setting up the free Visual Studio Code editor and starting with environments and requirements.txt.
